const ROUTE_PATHS = {
  Home: "/",
  About: "/about",
  Components: {
    index: "/components",
    Button: "/components/button",
    Card: "/components/card",
    Modal: "/components/modal",
    Drawer: "/components/drawer",
    Tabs: "/components/tabs",
    Tooltip: "/components/tooltip",
    Avatar: "/components/avatar",
    Badge: "/components/badge",
    Table: "/components/table",
    Form: "/components/form",
    Input: "/components/input",
    Select: "/components/select",
    Checkbox: "/components/checkbox",
    Radio: "/components/radio",
    Switch: "/components/switch",
    Accordion: "/components/accordion",
    Alert: "/components/alert",
    Breadcrumb: "/components/breadcrumb",
    Carousel: "/components/carousel",
    Pagination: "/components/pagination",
    ProgressBar: "/components/progress-bar",
    Spinner: "/components/spinner",
    Toast: "/components/toast",
    DatePicker: "/components/date-picker",
  },
  Documentation: "/documentation",
  Settings: "/settings",
};

export default ROUTE_PATHS;
